---
incompatible:
functional:
  - требование 1 Пользователь должен иметь возможность авторизоваться.
  - требование 2 Пользователь должен иметь возможность играть с ботом или с реальным пользователем по сети.
  - требование 3 Пользователь должен иметь возможность проверки своего решения.
  - требование 4 Пользователь должен иметь возможность увидеть, кто является победителем этой игры.
  - требование 5 Пользователь должен иметь возможность видеть код своего соперника в режиме он-лайн.
  - требование 6 Пользователь должен иметь возможность выбора языка.
  - требование 7 Пользователь должен иметь возможность видеть время игры, задание, чат.
  
non-functional:    
  - требование 1 Сайт должен иметь мобильную версию.
  - требование 2 Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - требование 3 Сайт должен быть способен обрабатывать большое количество трафика
  
implicit:
  - требование 1 Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - требование 2 Сайт должен быть безопасным и защищать данные пользователя.
  - требование 3 Пользователь должен иметь возможность находиться в игре неограниченное время.
  - требование 4 Пользователь не может редактировать  код соперника .
  - требование 5 Пользователь не может менять код после завершения игры- требование 
  - требование 6 Пользователь должен иметь возможность продолжать играть, если вдруг один из игроков вылетел из игры.
